# Generated by Django 6.0.3 on 2026-04-19 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fitnessclass",
            options={"verbose_name_plural": "Fitness classes"},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="experience",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="fitness_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="api.fitnessclass",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessclass",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="fitnessclass",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="api.trainer",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("user", "fitness_class", "status")},
        ),
    ]
